import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Layout from "../components/layout";

export default function Home() {
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Tech News</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <img
            src="/static/coding.jpg"
            alt="blue codes image"
            className={styles.mainImage}
          />
          <h1 className={styles.title}>Welcome to TECH NEWS</h1>
          <p className={styles.description}>
            The latest tech news about the world's best (and sometimes worst)
            programming languages, apps, companies and much more. From top
            companies like Google and Apple to tiny startups, Tech News has the
            latest for every coding updates that matters in technology daily.
          </p>
          <Link href="/news">
            <button className={styles.button}>News Now</button>
          </Link>
        </main>
      </div>
    </Layout>
  );
}
