import { useState } from "react";
import Head from "next/head";
import Router from "next/router";
import Layout from "../components/Layout";
import styles from "../styles/Home.module.css";

const News = ({ news }) => {
  const [searchQuery, setSearchQuery] = useState("apple");

  const handleSubmit = (e) => {
    e.preventDefault();
    Router.push(`/news/?searchTerm=${searchQuery}`);
  };

  return (
    <Layout>
      <Head>
        <title>Tech Headlines</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h2 className={styles.title}>TECH List</h2>
        <form onSubmit={handleSubmit}>
          <input
            type="text"
            placeholder="type coding language"
            value={searchQuery}
            onChange={(e) => {
              setSearchQuery(e.target.value);
            }}
            className={styles.input}
          />
          <button className={styles.button}>
            <span>Search</span>
          </button>
        </form>
        <hr />
        <div className={styles.grid}>
          {news.map((n, i) => {
            return (
              <p key={i} className={styles.card}>
                <a href={n.url} target="_blank">
                  {n.title}
                </a>
              </p>
            );
          })}
        </div>
      </div>
    </Layout>
  );
};

News.getInitialProps = async ({ query }) => {
  let news;
  try {
    const res = await fetch(
      `http://hn.algolia.com/api/v1/search?query=${query.searchTerm}`
    );
    news = await res.json();
  } catch (err) {
    console.log("ERROR", err);
    news = [];
  }
  return {
    news: news.hits,
  };
};

export default News;
